
services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "0.0.0.0:8081:8080"
    restart: always
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
