
services:
  backend:
    build: ./backend
    ports:
<<<<<<< HEAD
      - "0.0.0.0:8080:8080"
    env_file:
      - .env
=======
      - "8081:8080"
>>>>>>> e5b0a558ada60dbd128c0b5191c75c588de2b361
    restart: always
